import {
  type AutoImportOrderPackageType,
  type AutoImportRequestPackageType,
} from "~/contexts/AutoImportContext";
import {
  type ExportOrderPackageType,
  type ExportRequestPackageType,
} from "~/contexts/ExportContext";
import {
  type ImportOrderPackageType,
  type ImportRequestPackageType,
} from "~/contexts/ImportContext";
import { type NotificationItemType } from "~/contexts/NotificationContext";
import {
  type ShopOrderPackageType,
  type ShopRequestPackageType,
} from "~/contexts/ShopContext";

const src = "https://placehold.co/500x500/cac4d0/1d192b?text=Image"; // this is to simulate image source

// note: these are fake data and numbers are not exact, only for the purpose of not being empty

export const shopOrders: ShopOrderPackageType[] = [
  {
    orderId: "OD08751",
    orderStatus: "processed", // i think this is always "processed" for orders only
    orderLocalDate: new Date("2023/1/23").toLocaleString("en-US", {
      hour12: false,
    }), // this is to simulate ISO string from server converted to localString in frontend
    trackingId: "SH08751",
    shippingStatus: "not started", // not boolean
    originWarehouse: "Nigeria Warehouse (Lagos)",
    destinationWarehouse: "Nigeria Warehouse (Lagos)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
        properties: [
          // these are optional on the forms
          { label: "Color", value: "Blue" },
          { label: "Stripes", value: "5 inches" },
        ],
      },
      {
        store: "Aliexpress",
        urgent: true,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 126.66,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845", // phone number is string type not number because it is not used for calculations only for display
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "basic", // this is "basic" or "custom"
    totalShopForMeCost: 107.76, // sample aggregated data from items array
    shopForMeStatus: "Purchase not started", // this cannot be boolean because there is a third state: Purchase in progress
    totalShippingCost: 107.76, // sample aggregated data from items array
    shippingPaymentStatus: "Unpaid", // this can be boolean i think
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    orderId: "OD08752",
    orderStatus: "processed",
    orderLocalDate: new Date("2023/2/23").toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08752",
    shippingStatus: "arrived destination",
    originWarehouse: "US Warehouse (Richmond Texas)",
    destinationWarehouse: "Nigeria Warehouse (Lagos)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
      {
        store: "Aliexpress",
        urgent: true,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 126.66,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
      {
        store: "Others",
        urgent: true,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 126.66,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "basic",
    totalShopForMeCost: 107.76,
    shopForMeStatus: "Purchase in progress",
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Paid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    orderId: "OD08753",
    orderStatus: "processed",
    orderLocalDate: new Date("2023/3/23").toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08753",
    shippingStatus: "ready for shipping",
    originWarehouse: "China Warehouse (Guangzhou city)",
    destinationWarehouse: "Nigeria Warehouse (Lagos)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
      {
        store: "Aliexpress",
        urgent: true,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 126.66,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
      {
        store: "Others",
        urgent: true,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 126.66,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
      {
        store: "Others",
        urgent: true,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 126.66,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "basic",
    totalShopForMeCost: 107.76,
    shopForMeStatus: "Purchase completed",
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Unpaid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    orderId: "OD08754",
    orderStatus: "processed",
    orderLocalDate: new Date("2023/4/23").toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08754",
    shippingStatus: "in transit",
    originWarehouse: "Dubai Warehouse",
    destinationWarehouse: "Nigeria Warehouse (Lagos)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
      {
        store: "Aliexpress",
        urgent: true,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 126.66,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
      {
        store: "Others",
        urgent: true,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 126.66,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
      {
        store: "Others",
        urgent: true,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 126.66,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
      {
        store: "Others",
        urgent: true,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 126.66,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "basic",
    totalShopForMeCost: 107.76,
    shopForMeStatus: "Purchase completed",
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Paid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    orderId: "OD08755",
    orderStatus: "processed",
    orderLocalDate: new Date("2023/5/23").toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08755",
    shippingStatus: "processing",
    originWarehouse: "UK Warehouse (London)",
    destinationWarehouse: "Nigeria Warehouse (Lagos)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "basic",
    totalShopForMeCost: 107.76,
    shopForMeStatus: "Purchase completed",
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Paid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    orderId: "OD08756",
    orderStatus: "processed",
    orderLocalDate: new Date("2023/6/23").toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08756",
    shippingStatus: "cleared",
    originWarehouse: "US Warehouse (Richmond Texas)",
    destinationWarehouse: "Nigeria Warehouse (Lagos)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "basic",
    totalShopForMeCost: 107.76,
    shopForMeStatus: "Purchase completed",
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Paid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    orderId: "OD08757",
    orderStatus: "processed",
    orderLocalDate: new Date("2023/7/23").toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08757",
    shippingStatus: "cancelled",
    originWarehouse: "US Warehouse (Richmond Texas)",
    destinationWarehouse: "Nigeria Warehouse (Lagos)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "basic",
    totalShopForMeCost: 107.76,
    shopForMeStatus: "Purchase not started",
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Unpaid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    orderId: "OD08758",
    orderStatus: "processed",
    orderLocalDate: new Date("2023/8/23").toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08758",
    shippingStatus: "delivered",
    originWarehouse: "US Warehouse (Richmond Texas)",
    destinationWarehouse: "Nigeria Warehouse (Lagos)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "basic",
    totalShopForMeCost: 107.76,
    shopForMeStatus: "Purchase completed",
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Paid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
];

export const shopRequests: ShopRequestPackageType[] = [
  {
    requestId: "R08751",
    requestStatus: "Not Responded",
    requestLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
        properties: [
          { label: "Color", value: "Blue" },
          { label: "Stripes", value: "5 inches" },
        ],
      },
    ],
    packageCosts: {
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    requestId: "R08752",
    requestStatus: "Responded",
    requestLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    packageCosts: {
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    requestId: "R08753",
    requestStatus: "Not Responded",
    requestLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    packageCosts: {
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    requestId: "R08754",
    requestStatus: "Responded",
    requestLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    packageCosts: {
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    requestId: "R08755",
    requestStatus: "Not Responded",
    requestLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    packageCosts: {
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    requestId: "R08756",
    requestStatus: "Responded",
    requestLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    packageCosts: {
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
];

export const importOrders: ImportOrderPackageType[] = [
  {
    orderId: "OD08751",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08751",
    shippingStatus: "not started",
    originWarehouse: "US Warehouse (Richmond Texas)",
    destinationWarehouse: "Nigeria Warehouse (Lagos)",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "Not yet delivered",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
      },
    ],
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "basic",
    shippingPaymentStatus: "Unpaid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    orderId: "OD08752",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08752",
    shippingStatus: "arrived destination",
    originWarehouse: "US Warehouse (Richmond Texas)",
    destinationWarehouse: "Nigeria Warehouse (Lagos)",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "Not yet delivered",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
      },
    ],
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "basic",
    shippingPaymentStatus: "Paid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    orderId: "OD08754",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08754",
    shippingStatus: "in transit",
    originWarehouse: "US Warehouse (Richmond Texas)",
    destinationWarehouse: "Nigeria Warehouse (Lagos)",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "Not yet delivered",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
      },
    ],
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "basic",
    shippingPaymentStatus: "Paid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    orderId: "OD08755",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08755",
    shippingStatus: "processing",
    originWarehouse: "US Warehouse (Richmond Texas)",
    destinationWarehouse: "Nigeria Warehouse (Lagos)",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "Not yet delivered",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
      },
    ],
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "basic",
    shippingPaymentStatus: "Paid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    orderId: "OD08756",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08756",
    shippingStatus: "cleared",
    originWarehouse: "US Warehouse (Richmond Texas)",
    destinationWarehouse: "Nigeria Warehouse (Lagos)",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "Not yet delivered",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
      },
    ],
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "basic",
    shippingPaymentStatus: "Paid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    orderId: "OD08757",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08757",
    shippingStatus: "cancelled",
    originWarehouse: "US Warehouse (Richmond Texas)",
    destinationWarehouse: "Nigeria Warehouse (Lagos)",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "Not yet delivered",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
      },
    ],
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "basic",
    shippingPaymentStatus: "Unpaid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    orderId: "OD08758",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08758",
    shippingStatus: "delivered",
    originWarehouse: "US Warehouse (Richmond Texas)",
    destinationWarehouse: "Nigeria Warehouse (Lagos)",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "Not yet delivered",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
      },
    ],
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "basic",
    shippingPaymentStatus: "Paid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
];

export const importRequests: ImportRequestPackageType[] = [
  {
    requestId: "R08751",
    requestStatus: "Not Responded",
    requestLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    originWarehouse: "China Warehouse (Guangzhou city)",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "Delivered",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
      },
    ],
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    requestId: "R08752",
    requestStatus: "Responded",
    requestLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    originWarehouse: "Dubai Warehouse",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "Not yet delivered",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
      },
    ],
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    requestId: "R08753",
    requestStatus: "Not Responded",
    requestLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    originWarehouse: "Nigeria Warehouse (Lagos)",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "Delivered",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
      },
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "Not yet delivered",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
      },
    ],
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    requestId: "R08754",
    requestStatus: "Responded",
    requestLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    originWarehouse: "UK Warehouse (London)",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "Delivered",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
      },
    ],
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    requestId: "R08755",
    requestStatus: "Not Responded",
    requestLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "Not yet delivered",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
      },
    ],
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    requestId: "R08756",
    requestStatus: "Responded",
    requestLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "Not yet delivered",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
      },
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "Delivered",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
      },
    ],
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
];

export const exportOrders: ExportOrderPackageType[] = [
  {
    orderId: "OD08751",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08751",
    shippingStatus: "not started",
    originWarehouse: "US Warehouse (Richmond Texas)",
    destinationDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "Not yet delivered",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
      },
    ],
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "basic",
    shippingPaymentStatus: "Unpaid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    orderId: "OD08752",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08752",
    shippingStatus: "arrived destination",
    originWarehouse: "US Warehouse (Richmond Texas)",
    destinationDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "Not yet delivered",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
      },
    ],
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "basic",
    shippingPaymentStatus: "Paid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    orderId: "OD08754",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08754",
    shippingStatus: "in transit",
    originWarehouse: "US Warehouse (Richmond Texas)",
    destinationDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "Not yet delivered",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
      },
    ],
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "basic",
    shippingPaymentStatus: "Paid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    orderId: "OD08755",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08755",
    shippingStatus: "processing",
    originWarehouse: "US Warehouse (Richmond Texas)",
    destinationDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "Not yet delivered",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
      },
    ],
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "basic",
    shippingPaymentStatus: "Paid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    orderId: "OD08756",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08756",
    shippingStatus: "cleared",
    originWarehouse: "US Warehouse (Richmond Texas)",
    destinationDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "Not yet delivered",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
      },
    ],
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "basic",
    shippingPaymentStatus: "Paid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    orderId: "OD08757",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08757",
    shippingStatus: "cancelled",
    originWarehouse: "US Warehouse (Richmond Texas)",
    destinationDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "Not yet delivered",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
      },
    ],
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "basic",
    shippingPaymentStatus: "Unpaid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    orderId: "OD08758",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08758",
    shippingStatus: "delivered",
    originWarehouse: "US Warehouse (Richmond Texas)",
    destinationDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "Not yet delivered",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        weight: 67,
        height: 5,
        length: 5,
        width: 5,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
      },
    ],
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "basic",
    shippingPaymentStatus: "Paid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
];

export const exportRequests: ExportRequestPackageType[] = importRequests;

export const autoImportOrders: AutoImportOrderPackageType[] = [
  {
    orderId: "OD08756",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08756",
    shippingStatus: "not started",
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        brand: "asd",
        model: "asd",
        productionYear: "2023",
        value: 107.76,
        condition: "Drivable", // this can be boolean
        color: "blue",
        mileage: 0,
        vin: "asdaasd123123",
        url: "https://www.asd.com/asdasd",
        image: src,
        carTitleCopy: src,
        description: "asdasdasdasd",
        pickupDetails: {
          firstName: "Malibu",
          lastName: "SHedrack",
          countryCode: "+234",
          phoneNumber: "803 456 7845",
          email: "Malibushdrack@gmail.com",
          address: "No, 1osolo way, ikeja road, behind scaint merry",
          country: "NG",
          state: "LA",
          city: "Ikeja",
          zipPostalCode: "98765",
          pickUpDate: new Date(
            new Date().valueOf() + 24 * 60 * 60 * 1000,
          ).toLocaleDateString(),
          locationType: "Mosque",
          pickupCost: 22.0,
        },
      },
    ],
    destinationDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "custom",
    shippingPaymentStatus: "Unpaid",
    clearingPaymentStatus: "Unpaid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    orderId: "OD08755",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08755",
    shippingStatus: "arrived destination",
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        brand: "asd",
        model: "asd",
        productionYear: "2023",
        value: 107.76,
        condition: "Drivable",
        color: "blue",
        mileage: 0,
        vin: "asdaasd123123",
        url: "https://www.asd.com/asdasd",
        image: src,
        carTitleCopy: src,
        description: "asdasdasdasd",
        pickupDetails: {
          firstName: "Malibu",
          lastName: "SHedrack",
          countryCode: "+234",
          phoneNumber: "803 456 7845",
          email: "Malibushdrack@gmail.com",
          address: "No, 1osolo way, ikeja road, behind scaint merry",
          country: "NG",
          state: "LA",
          city: "Ikeja",
          zipPostalCode: "98765",
          pickUpDate: new Date(
            new Date().valueOf() + 24 * 60 * 60 * 1000,
          ).toLocaleDateString(),
          locationType: "Mosque",
          pickupCost: 22.0,
        },
      },
    ],
    destinationDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "custom",
    shippingPaymentStatus: "Paid",
    clearingPaymentStatus: "Unpaid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    orderId: "OD08754",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08754",
    shippingStatus: "cleared",
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        brand: "asd",
        model: "asd",
        productionYear: "2023",
        value: 107.76,
        condition: "Drivable",
        color: "blue",
        mileage: 0,
        vin: "asdaasd123123",
        url: "https://www.asd.com/asdasd",
        image: src,
        carTitleCopy: src,
        description: "asdasdasdasd",
      },
    ],
    destinationDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "custom",
    shippingPaymentStatus: "Paid",
    clearingPaymentStatus: "Paid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    orderId: "OD08753",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08753",
    shippingStatus: "processing",
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        brand: "asd",
        model: "asd",
        productionYear: "2023",
        value: 107.76,
        condition: "Drivable",
        color: "blue",
        mileage: 0,
        vin: "asdaasd123123",
        url: "https://www.asd.com/asdasd",
        image: src,
        carTitleCopy: src,
        description: "asdasdasdasd",
      },
    ],
    destinationDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "custom",
    shippingPaymentStatus: "Paid",
    clearingPaymentStatus: "Unpaid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },

  {
    orderId: "OD08752",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08752",
    shippingStatus: "in transit",
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        brand: "asd",
        model: "asd",
        productionYear: "2023",
        value: 107.76,
        condition: "Drivable",
        color: "blue",
        mileage: 0,
        vin: "asdaasd123123",
        url: "https://www.asd.com/asdasd",
        image: src,
        carTitleCopy: src,
        description: "asdasdasdasd",
      },
    ],
    destinationDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "custom",
    shippingPaymentStatus: "Paid",
    clearingPaymentStatus: "Unpaid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },

  {
    orderId: "OD08751",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08751",
    shippingStatus: "arrived destination",
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        brand: "asd",
        model: "asd",
        productionYear: "2023",
        value: 107.76,
        condition: "Drivable",
        color: "blue",
        mileage: 0,
        vin: "asdaasd123123",
        url: "https://www.asd.com/asdasd",
        image: src,
        carTitleCopy: src,
        description: "asdasdasdasd",
      },
    ],
    destinationDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "custom",
    shippingPaymentStatus: "Paid",
    clearingPaymentStatus: "Unpaid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    orderId: "OD08750",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    trackingId: "SH08750",
    shippingStatus: "delivered",
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        brand: "asd",
        model: "asd",
        productionYear: "2023",
        value: 107.76,
        condition: "Drivable",
        color: "blue",
        mileage: 0,
        vin: "asdaasd123123",
        url: "https://www.asd.com/asdasd",
        image: src,
        carTitleCopy: src,
        description: "asdasdasdasd",
      },
    ],
    destinationDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "custom",
    shippingPaymentStatus: "Paid",
    clearingPaymentStatus: "Paid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
];

export const autoImportRequests: AutoImportRequestPackageType[] = [
  {
    requestId: "R08756",
    requestStatus: "Responded",
    requestLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        brand: "asd",
        model: "asd",
        productionYear: "2023",
        value: 107.76,
        condition: "Drivable",
        color: "blue",
        mileage: 0,
        vin: "asdaasd123123",
        url: "https://www.asd.com/asdasd",
        image: src,
        carTitleCopy: src,
        description: "asdasdasdasd",
        pickupDetails: {
          firstName: "Malibu",
          lastName: "SHedrack",
          countryCode: "+234",
          phoneNumber: "803 456 7845",
          email: "Malibushdrack@gmail.com",
          address: "No, 1osolo way, ikeja road, behind scaint merry",
          country: "NG",
          state: "LA",
          city: "Ikeja",
          zipPostalCode: "98765",
          pickUpDate: new Date(
            new Date().valueOf() + 24 * 60 * 60 * 1000,
          ).toLocaleDateString(),
          locationType: "Mosque",
          pickupCost: 22.0,
        },
      },
    ],
    destinationDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "custom",
    shippingPaymentStatus: "Unpaid",
    clearingPaymentStatus: "Unpaid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
  {
    requestId: "R08755",
    requestStatus: "Not Responded",
    requestLocalDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        brand: "asd",
        model: "asd",
        productionYear: "2023",
        value: 107.76,
        condition: "Drivable",
        color: "blue",
        mileage: 0,
        vin: "asdaasd123123",
        url: "https://www.asd.com/asdasd",
        image: src,
        carTitleCopy: src,
        description: "asdasdasdasd",
      },
    ],
    destinationDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "NG",
      state: "LA",
      city: "Ikeja",
      zipPostalCode: "10011",
    },
    shippingMethod: "custom",
    shippingPaymentStatus: "Unpaid",
    clearingPaymentStatus: "Unpaid",
    packageCosts: {
      shippingCost: 126.66,
      clearingPortHandlingCost: 126.66,
      otherCharges: 126.66,
      storageCharge: 126.66,
      insurance: 126.66,
      valueAddedTax: 126.66,
      paymentMethodSurcharge: 126.66,
      discount: 126.66,
    },
  },
];

export const notificationItems: NotificationItemType[] = [
  {
    localDate: new Date().toLocaleString("en-US", {
      hour12: false,
    }),
    type: "payment confirmation",
    order: shopOrders[2]!,
  },
  {
    localDate: new Date("2022/12/12").toLocaleString("en-US", {
      hour12: false,
    }),
    type: "shipment arrival",
    order: shopOrders[2]!,
  },
  {
    localDate: new Date("2023/2/23").toLocaleString("en-US", {
      hour12: false,
    }),
    type: "payment rejection",
    order: shopOrders[0]!,
  },
];
